# Example hyperparameters for DQN on CartPole-v1
agent:
  type: dqn
  hidden_dims: [128, 128]
  lr: 0.0005
  gamma: 0.99
  tau: 0.005
  target_update_interval: 50
  min_buffer_size: 5000
  exploration_epsilon: 0.1
trainer:
  total_steps: 100000
  eval_interval: 10000
